{{/*
Copyright 2023. Hancom Inc. All rights reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "documentviewer.fullname" . }}-filter
  labels:
    app: documentviewer-filter
  {{- include "documentviewer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.documentviewerFilter.service.type }}
  selector:
    app: documentviewer-filter
  {{- include "documentviewer.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.documentviewerFilter.service.port }}
      targetPort: 8101
      protocol: TCP
      name: tcp
